import './globals.css'
import { Inter } from 'next/font/google'
import styles from './page.module.css'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className + " " + styles.body}>
        <Header />
        {children}
      </body>
    </html>
  )
}
